### PR TITLE
Fixed issue with starting input not being passed from child workflow

### PR DESCRIPTION
**Pull request by mattstrom**

### CODE REVIEW

**Comment by mattstrom** [comment]
Thanks for the prompt update, @sdebnath! Could you also update the NuGet package?

**Comment by sdebnath** [comment]
I thought you had access to nuget? It will take me a day or two to get VS/Windows VM up and running.

**Comment by mattstrom** [comment]
I myself do not, but Michael does. I'll see if he can do it.

**Comment by sdebnath** [comment]
Sounds good, let me know otherwise.

**Comment by mattstrom** [comment]
Will do. I certainly don't want you wasting time setting up a VM just for this.

**Comment by sdebnath** [comment]
Any luck with this?

**Comment by mattstrom** [comment]
My apologies. Michael was able to push an update to NuGet.

I should have mention the first time that I had already built the .nupkg; I
just needed it uploaded. So you wouldn't have needed to stand up a Windows
VM for that.

**Comment by sdebnath** [comment]
Yikes, okay next time I can take care of that :)

**Pull request merged**
